
spring:
  application:
    name: API-GATEWAY

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userService-client
          uri: lb://userService-client
          predicates:
            - Path=/api/user/**

        - id: inventoryService-client
          uri: lb://inventoryService-client
          predicates:
            - Path=/api/inventory/**

        - id: orderService-client
          uri: lb://orderService-client
          predicates:
            - Path=/api/order/**

        - id: userService-client
          uri: lb://orderService-client
          predicates:
            - Path=/api/user/**

        - id: productService-client
          uri: lb://productService-client
          predicates:
            - Path=/productService-client

        - id: authServer-client
          uri: lb://authServer-client
          predicates:
            - Path=api/auth/**

server:
  port: 8080

