spring:
  application:
    name: userService-client
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8084

inventory:
  domain: http://localhost:8081

product:
  domain: http://localhost:8082

order:
  domain: http://localhost:8083
