spring:
  application:
    name: productService-client
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082


inventory:
  domain: http://inventoryService-client

order:
  domain: http://orderService-client

user:
  domain: http://userService-client