spring:
  application:
    name: inventoryService-client
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-service
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081

order:
  domain: http://orderService-client

product:
  domain: http://orderService-client

user:
  domain: http://userService-client
