package org.example.domain.enumuration;

public enum OrderStatus {
    ORDER_PENDING, ORDER_APPROVED, ON_THE_WAY, DELIVERY_FAILED, DELIVERY_SUCCESS, CANCELLATION_REQUESTED, CANCELLATION_REJECTED, CANCELLATION_APPROVED, ORDER_REJECTED
}
